---
version: v1
log_file: "/Users/nashgadre/workspace/moxie/test1/moxie.log"
status_page: "localhost:8443"
services:
  - name: "Assets 1"
    type: static
    ingress_url: "app1.localhost:8443"
    egress_url: "/Users/nashgadre/workspace/moxie/test1"
  - name: "Assets 2"
    type: static
    ingress_url: "app2.localhost:8443"
    egress_url: "/Users/nashgadre/workspace/moxie/test2"
  - name: "Web Proxy Service"
    type: proxy
    ingress_url: "api.localhost:8443"
    egress_url: "http://localhost:8000/admin/"
